package transfusionsanguine;


import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class Check2 extends javax.swing.JFrame {
Connection conn ;
PreparedStatement pst ,pstsel ;
ResultSet rs;
public static int checkpage=0;
     
    public Check2() {
        initComponents();
         conn = Transfusion.conn();
         jMenu7.setText(login1.username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        buttonGroup14 = new javax.swing.ButtonGroup();
        buttonGroup15 = new javax.swing.ButtonGroup();
        buttonGroup16 = new javax.swing.ButtonGroup();
        buttonGroup17 = new javax.swing.ButtonGroup();
        buttonGroup18 = new javax.swing.ButtonGroup();
        buttonGroup19 = new javax.swing.ButtonGroup();
        buttonGroup20 = new javax.swing.ButtonGroup();
        fcontrole = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        poulpre = new javax.swing.JTextField();
        tapre = new javax.swing.JTextField();
        cons = new javax.swing.JTextField();
        tpre = new javax.swing.JTextField();
        into = new javax.swing.JTextField();
        tapost = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tpost = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        resulcronon = new javax.swing.JCheckBox();
        resulcrooui = new javax.swing.JCheckBox();
        jLabel28 = new javax.swing.JLabel();
        painfooui = new javax.swing.JCheckBox();
        jLabel29 = new javax.swing.JLabel();
        painfonon = new javax.swing.JCheckBox();
        jLabel30 = new javax.swing.JLabel();
        voieoui = new javax.swing.JCheckBox();
        jLabel31 = new javax.swing.JLabel();
        voienon = new javax.swing.JCheckBox();
        jLabel32 = new javax.swing.JLabel();
        uloui = new javax.swing.JCheckBox();
        jLabel33 = new javax.swing.JLabel();
        ulnon = new javax.swing.JCheckBox();
        jLabel34 = new javax.swing.JLabel();
        resuroui = new javax.swing.JCheckBox();
        jLabel35 = new javax.swing.JLabel();
        resurnon = new javax.swing.JCheckBox();
        poulpost = new javax.swing.JTextField();
        ras = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        connfsoui = new javax.swing.JCheckBox();
        jLabel37 = new javax.swing.JLabel();
        connfsnon = new javax.swing.JCheckBox();
        jLabel40 = new javax.swing.JLabel();
        traoui = new javax.swing.JCheckBox();
        jLabel41 = new javax.swing.JLabel();
        tranon = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        pslnon = new javax.swing.JCheckBox();
        jLabel43 = new javax.swing.JLabel();
        psloui = new javax.swing.JCheckBox();
        presnon = new javax.swing.JCheckBox();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        presoui = new javax.swing.JCheckBox();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        nfsoui = new javax.swing.JCheckBox();
        jLabel49 = new javax.swing.JLabel();
        nfsnon = new javax.swing.JCheckBox();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        gsoui = new javax.swing.JCheckBox();
        jLabel52 = new javax.swing.JLabel();
        gsnon = new javax.swing.JCheckBox();
        jLabel54 = new javax.swing.JLabel();
        phenonon = new javax.swing.JCheckBox();
        phenooui = new javax.swing.JCheckBox();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        condtranoui = new javax.swing.JCheckBox();
        jLabel58 = new javax.swing.JLabel();
        condtrannon = new javax.swing.JCheckBox();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        bondonoui = new javax.swing.JCheckBox();
        jLabel61 = new javax.swing.JLabel();
        bondonnon = new javax.swing.JCheckBox();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        conidenoui = new javax.swing.JCheckBox();
        jLabel65 = new javax.swing.JLabel();
        conidennon = new javax.swing.JCheckBox();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        conformoui = new javax.swing.JCheckBox();
        jLabel68 = new javax.swing.JLabel();
        conformnon = new javax.swing.JCheckBox();
        jLabel69 = new javax.swing.JLabel();
        gpsl = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        dateveroui = new javax.swing.JCheckBox();
        jLabel72 = new javax.swing.JLabel();
        datevernon = new javax.swing.JCheckBox();
        jLabel73 = new javax.swing.JLabel();
        date1 = new com.toedter.calendar.JDateChooser();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        prosangoui = new javax.swing.JCheckBox();
        jLabel76 = new javax.swing.JLabel();
        prosangnon = new javax.swing.JCheckBox();
        jLabel77 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        observ = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        veridenoui = new javax.swing.JCheckBox();
        jLabel79 = new javax.swing.JLabel();
        veridennon = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        episode = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        respost = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        fcontrole.setBackground(new java.awt.Color(204, 228, 232));
        fcontrole.setLayout(null);

        jLabel23.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Pré-transfusion");
        fcontrole.add(jLabel23);
        jLabel23.setBounds(50, 250, 203, 20);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Test ultime au lit fait ");
        fcontrole.add(jLabel2);
        jLabel2.setBounds(50, 430, 450, 19);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Etat de conscience ");
        fcontrole.add(jLabel3);
        jLabel3.setBounds(580, 730, 160, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Patient informé et consentement transfusionnel du patient signé ");
        fcontrole.add(jLabel4);
        jLabel4.setBounds(50, 310, 450, 19);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Vérification de l'identité du patient ");
        fcontrole.add(jLabel5);
        jLabel5.setBounds(50, 340, 450, 19);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Voie veineuse ou périphérique perméable");
        fcontrole.add(jLabel7);
        jLabel7.setBounds(50, 400, 450, 19);

        jLabel24.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Post-transfusion");
        fcontrole.add(jLabel24);
        jLabel24.setBounds(50, 520, 203, 20);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Résultats de la surveillance (10 mn pendant la transfusion)");
        fcontrole.add(jLabel8);
        jLabel8.setBounds(50, 550, 460, 19);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Résultats :");
        fcontrole.add(jLabel9);
        jLabel9.setBounds(50, 580, 80, 19);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Contrôle NFS post transfusion");
        fcontrole.add(jLabel10);
        jLabel10.setBounds(50, 610, 280, 19);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Résultats ");
        fcontrole.add(jLabel11);
        jLabel11.setBounds(50, 640, 90, 19);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Traçabilité dans le registre transfusionnel ");
        fcontrole.add(jLabel12);
        jLabel12.setBounds(50, 670, 450, 19);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Paramètres vitaux post transfusionnel :");
        fcontrole.add(jLabel13);
        jLabel13.setBounds(50, 700, 450, 19);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Le résultat du cross match récupéré ");
        fcontrole.add(jLabel14);
        jLabel14.setBounds(50, 280, 375, 19);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Intolérance");
        fcontrole.add(jLabel15);
        jLabel15.setBounds(290, 580, 120, 19);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("TA");
        fcontrole.add(jLabel16);
        jLabel16.setBounds(260, 730, 30, 30);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Etat du patient ");
        fcontrole.add(jLabel17);
        jLabel17.setBounds(50, 370, 140, 20);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Pouls");
        fcontrole.add(jLabel18);
        jLabel18.setBounds(230, 370, 60, 19);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("TA");
        fcontrole.add(jLabel19);
        jLabel19.setBounds(380, 370, 30, 19);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("T°");
        fcontrole.add(jLabel20);
        jLabel20.setBounds(510, 370, 30, 19);

        jLabel21.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Pouls");
        fcontrole.add(jLabel21);
        jLabel21.setBounds(80, 730, 60, 30);

        jLabel22.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("RAS");
        fcontrole.add(jLabel22);
        jLabel22.setBounds(160, 580, 60, 19);
        fcontrole.add(poulpre);
        poulpre.setBounds(280, 370, 50, 29);
        fcontrole.add(tapre);
        tapre.setBounds(420, 370, 50, 29);
        fcontrole.add(cons);
        cons.setBounds(730, 730, 50, 29);
        fcontrole.add(tpre);
        tpre.setBounds(540, 370, 50, 29);
        fcontrole.add(into);
        into.setBounds(390, 580, 50, 29);
        fcontrole.add(tapost);
        tapost.setBounds(300, 730, 50, 29);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("T°");
        fcontrole.add(jLabel6);
        jLabel6.setBounds(420, 730, 30, 30);
        fcontrole.add(tpost);
        tpost.setBounds(450, 730, 50, 29);

        jLabel26.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Oui");
        fcontrole.add(jLabel26);
        jLabel26.setBounds(640, 280, 30, 20);

        jLabel27.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("Non");
        fcontrole.add(jLabel27);
        jLabel27.setBounds(730, 280, 28, 19);

        buttonGroup13.add(resulcronon);
        resulcronon.setSelected(true);
        fcontrole.add(resulcronon);
        resulcronon.setBounds(770, 280, 25, 25);

        buttonGroup13.add(resulcrooui);
        fcontrole.add(resulcrooui);
        resulcrooui.setBounds(680, 280, 25, 25);

        jLabel28.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel28.setText("Oui");
        fcontrole.add(jLabel28);
        jLabel28.setBounds(640, 310, 30, 20);

        buttonGroup14.add(painfooui);
        fcontrole.add(painfooui);
        painfooui.setBounds(680, 310, 25, 25);

        jLabel29.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("Non");
        fcontrole.add(jLabel29);
        jLabel29.setBounds(730, 310, 28, 19);

        buttonGroup14.add(painfonon);
        painfonon.setSelected(true);
        fcontrole.add(painfonon);
        painfonon.setBounds(770, 310, 25, 25);

        jLabel30.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel30.setText("Oui");
        fcontrole.add(jLabel30);
        jLabel30.setBounds(640, 400, 30, 20);

        buttonGroup16.add(voieoui);
        fcontrole.add(voieoui);
        voieoui.setBounds(680, 400, 25, 25);

        jLabel31.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel31.setText("Non");
        fcontrole.add(jLabel31);
        jLabel31.setBounds(730, 400, 28, 19);

        buttonGroup16.add(voienon);
        voienon.setSelected(true);
        fcontrole.add(voienon);
        voienon.setBounds(770, 400, 25, 25);

        jLabel32.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel32.setText("Oui");
        fcontrole.add(jLabel32);
        jLabel32.setBounds(640, 430, 30, 20);

        buttonGroup17.add(uloui);
        fcontrole.add(uloui);
        uloui.setBounds(680, 430, 25, 25);

        jLabel33.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel33.setText("Non");
        fcontrole.add(jLabel33);
        jLabel33.setBounds(730, 430, 28, 19);

        buttonGroup17.add(ulnon);
        ulnon.setSelected(true);
        fcontrole.add(ulnon);
        ulnon.setBounds(770, 430, 25, 25);

        jLabel34.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel34.setText("Oui");
        fcontrole.add(jLabel34);
        jLabel34.setBounds(640, 550, 30, 20);

        buttonGroup18.add(resuroui);
        fcontrole.add(resuroui);
        resuroui.setBounds(680, 550, 25, 25);

        jLabel35.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel35.setText("Non");
        fcontrole.add(jLabel35);
        jLabel35.setBounds(730, 550, 28, 19);

        buttonGroup18.add(resurnon);
        resurnon.setSelected(true);
        fcontrole.add(resurnon);
        resurnon.setBounds(770, 550, 25, 25);
        fcontrole.add(poulpost);
        poulpost.setBounds(150, 730, 50, 29);
        fcontrole.add(ras);
        ras.setBounds(210, 580, 50, 29);

        jLabel36.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel36.setText("Oui");
        fcontrole.add(jLabel36);
        jLabel36.setBounds(640, 610, 30, 20);

        buttonGroup12.add(connfsoui);
        fcontrole.add(connfsoui);
        connfsoui.setBounds(680, 610, 25, 25);

        jLabel37.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel37.setText("Non");
        fcontrole.add(jLabel37);
        jLabel37.setBounds(730, 610, 28, 19);

        buttonGroup12.add(connfsnon);
        connfsnon.setSelected(true);
        fcontrole.add(connfsnon);
        connfsnon.setBounds(770, 610, 25, 25);

        jLabel40.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel40.setText("Oui");
        fcontrole.add(jLabel40);
        jLabel40.setBounds(640, 670, 30, 20);

        buttonGroup20.add(traoui);
        fcontrole.add(traoui);
        traoui.setBounds(680, 670, 25, 25);

        jLabel41.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel41.setText("Non");
        fcontrole.add(jLabel41);
        jLabel41.setBounds(730, 670, 28, 19);

        buttonGroup20.add(tranon);
        tranon.setSelected(true);
        fcontrole.add(tranon);
        tranon.setBounds(770, 670, 25, 25);

        jButton1.setText("Enregistrer ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        fcontrole.add(jButton1);
        jButton1.setBounds(1300, 840, 170, 60);

        jLabel25.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("Prescription médicale datée et signée par le médecin ");
        fcontrole.add(jLabel25);
        jLabel25.setBounds(890, 190, 390, 19);

        jLabel42.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel42.setText("Oui");
        fcontrole.add(jLabel42);
        jLabel42.setBounds(1320, 220, 24, 19);

        buttonGroup2.add(pslnon);
        pslnon.setSelected(true);
        fcontrole.add(pslnon);
        pslnon.setBounds(1360, 220, 25, 25);

        jLabel43.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel43.setText("Non");
        fcontrole.add(jLabel43);
        jLabel43.setBounds(1390, 190, 28, 19);

        buttonGroup2.add(psloui);
        fcontrole.add(psloui);
        psloui.setBounds(1300, 220, 25, 25);

        buttonGroup1.add(presnon);
        presnon.setSelected(true);
        fcontrole.add(presnon);
        presnon.setBounds(1360, 190, 25, 25);

        jLabel44.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel44.setText("Non");
        fcontrole.add(jLabel44);
        jLabel44.setBounds(1390, 220, 28, 19);

        jLabel45.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel45.setText("Oui");
        fcontrole.add(jLabel45);
        jLabel45.setBounds(1320, 190, 24, 19);

        buttonGroup1.add(presoui);
        fcontrole.add(presoui);
        presoui.setBounds(1300, 190, 25, 25);

        jLabel46.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel46.setText("Demande du PSL");
        fcontrole.add(jLabel46);
        jLabel46.setBounds(890, 220, 125, 19);

        jLabel47.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel47.setText("Copie NFS");
        fcontrole.add(jLabel47);
        jLabel47.setBounds(890, 250, 79, 19);

        jLabel48.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel48.setText("Oui");
        fcontrole.add(jLabel48);
        jLabel48.setBounds(1320, 250, 24, 19);

        buttonGroup3.add(nfsoui);
        fcontrole.add(nfsoui);
        nfsoui.setBounds(1300, 250, 25, 25);

        jLabel49.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel49.setText("Non");
        fcontrole.add(jLabel49);
        jLabel49.setBounds(1390, 250, 28, 19);

        buttonGroup3.add(nfsnon);
        nfsnon.setSelected(true);
        fcontrole.add(nfsnon);
        nfsnon.setBounds(1360, 250, 25, 25);

        jLabel50.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel50.setText("Phénotype ");
        fcontrole.add(jLabel50);
        jLabel50.setBounds(890, 310, 300, 19);

        jLabel51.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel51.setText("Oui");
        fcontrole.add(jLabel51);
        jLabel51.setBounds(1320, 280, 40, 19);

        buttonGroup4.add(gsoui);
        fcontrole.add(gsoui);
        gsoui.setBounds(1300, 280, 60, 25);

        jLabel52.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel52.setText("Non");
        fcontrole.add(jLabel52);
        jLabel52.setBounds(1390, 280, 250, 19);

        buttonGroup4.add(gsnon);
        gsnon.setSelected(true);
        fcontrole.add(gsnon);
        gsnon.setBounds(1360, 280, 240, 25);

        jLabel54.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel54.setText("Non");
        fcontrole.add(jLabel54);
        jLabel54.setBounds(1390, 310, 28, 19);

        buttonGroup5.add(phenonon);
        phenonon.setSelected(true);
        fcontrole.add(phenonon);
        phenonon.setBounds(1360, 310, 25, 25);

        buttonGroup5.add(phenooui);
        fcontrole.add(phenooui);
        phenooui.setBounds(1300, 310, 25, 25);

        jLabel55.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel55.setText("Oui");
        fcontrole.add(jLabel55);
        jLabel55.setBounds(1320, 310, 24, 19);

        jLabel56.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel56.setText("GS");
        fcontrole.add(jLabel56);
        jLabel56.setBounds(890, 280, 23, 19);

        jLabel53.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel53.setText("Conditions de transport respectées");
        fcontrole.add(jLabel53);
        jLabel53.setBounds(890, 340, 320, 19);

        jLabel57.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel57.setText("Oui");
        fcontrole.add(jLabel57);
        jLabel57.setBounds(1320, 340, 24, 19);

        buttonGroup6.add(condtranoui);
        fcontrole.add(condtranoui);
        condtranoui.setBounds(1300, 340, 25, 25);

        jLabel58.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel58.setText("Non");
        fcontrole.add(jLabel58);
        jLabel58.setBounds(1390, 340, 28, 19);

        buttonGroup6.add(condtrannon);
        condtrannon.setSelected(true);
        fcontrole.add(condtrannon);
        condtrannon.setBounds(1360, 340, 25, 25);

        jLabel59.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel59.setText("Bon du donneur récupéré");
        fcontrole.add(jLabel59);
        jLabel59.setBounds(890, 370, 200, 19);

        jLabel60.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel60.setText("Oui");
        fcontrole.add(jLabel60);
        jLabel60.setBounds(1320, 370, 24, 19);

        buttonGroup7.add(bondonoui);
        fcontrole.add(bondonoui);
        bondonoui.setBounds(1300, 370, 25, 25);

        jLabel61.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel61.setText("Non");
        fcontrole.add(jLabel61);
        jLabel61.setBounds(1390, 370, 28, 19);

        buttonGroup7.add(bondonnon);
        bondonnon.setSelected(true);
        fcontrole.add(bondonnon);
        bondonnon.setBounds(1360, 370, 25, 25);

        jLabel62.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel62.setText("A la reception de sang");
        fcontrole.add(jLabel62);
        jLabel62.setBounds(880, 450, 230, 20);

        jLabel63.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel63.setText("Concordance entre identité du patient et formulaire de demande");
        fcontrole.add(jLabel63);
        jLabel63.setBounds(880, 480, 470, 19);

        jLabel64.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel64.setText("Oui");
        fcontrole.add(jLabel64);
        jLabel64.setBounds(1430, 480, 24, 19);

        buttonGroup8.add(conidenoui);
        fcontrole.add(conidenoui);
        conidenoui.setBounds(1410, 480, 25, 25);

        jLabel65.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel65.setText("Non");
        fcontrole.add(jLabel65);
        jLabel65.setBounds(1480, 480, 28, 19);

        buttonGroup8.add(conidennon);
        conidennon.setSelected(true);
        fcontrole.add(conidennon);
        conidennon.setBounds(1460, 480, 25, 25);

        jLabel66.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel66.setText("Concordance entre formulaire de demande et poches de sang réceptionné");
        fcontrole.add(jLabel66);
        jLabel66.setBounds(880, 510, 530, 19);

        jLabel67.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel67.setText("Oui");
        fcontrole.add(jLabel67);
        jLabel67.setBounds(1430, 510, 24, 19);

        buttonGroup9.add(conformoui);
        fcontrole.add(conformoui);
        conformoui.setBounds(1410, 510, 25, 25);

        jLabel68.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel68.setText("Non");
        fcontrole.add(jLabel68);
        jLabel68.setBounds(1480, 510, 28, 19);

        buttonGroup9.add(conformnon);
        conformnon.setSelected(true);
        fcontrole.add(conformnon);
        conformnon.setBounds(1460, 510, 25, 25);

        jLabel69.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel69.setText("Groupe du PSL");
        fcontrole.add(jLabel69);
        jLabel69.setBounds(880, 540, 200, 19);
        fcontrole.add(gpsl);
        gpsl.setBounds(1410, 540, 100, 29);

        jLabel70.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel70.setText("Date de péremption vérifiée");
        fcontrole.add(jLabel70);
        jLabel70.setBounds(880, 570, 194, 19);

        jLabel71.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel71.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel71.setText("Oui");
        fcontrole.add(jLabel71);
        jLabel71.setBounds(1430, 570, 24, 19);

        buttonGroup10.add(dateveroui);
        fcontrole.add(dateveroui);
        dateveroui.setBounds(1410, 570, 25, 25);

        jLabel72.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel72.setText("Non");
        fcontrole.add(jLabel72);
        jLabel72.setBounds(1480, 570, 28, 19);

        buttonGroup10.add(datevernon);
        datevernon.setSelected(true);
        fcontrole.add(datevernon);
        datevernon.setBounds(1460, 570, 25, 25);

        jLabel73.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel73.setText("Date");
        fcontrole.add(jLabel73);
        jLabel73.setBounds(880, 610, 34, 19);
        fcontrole.add(date1);
        date1.setBounds(1410, 600, 100, 29);

        jLabel74.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel74.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel74.setText("Produit sanguin bien conservé (la couleur, l'aspect des PSL)");
        fcontrole.add(jLabel74);
        jLabel74.setBounds(880, 640, 440, 19);

        jLabel75.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel75.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel75.setText("Oui");
        fcontrole.add(jLabel75);
        jLabel75.setBounds(1430, 640, 24, 20);

        buttonGroup11.add(prosangoui);
        fcontrole.add(prosangoui);
        prosangoui.setBounds(1410, 640, 25, 25);

        jLabel76.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel76.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel76.setText("Non");
        fcontrole.add(jLabel76);
        jLabel76.setBounds(1480, 640, 28, 19);

        buttonGroup11.add(prosangnon);
        prosangnon.setSelected(true);
        fcontrole.add(prosangnon);
        prosangnon.setBounds(1460, 640, 25, 25);

        jLabel77.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel77.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel77.setText("Observations :");
        fcontrole.add(jLabel77);
        jLabel77.setBounds(880, 670, 130, 19);

        observ.setColumns(20);
        observ.setRows(5);
        jScrollPane1.setViewportView(observ);

        fcontrole.add(jScrollPane1);
        jScrollPane1.setBounds(880, 700, 530, 70);

        jLabel1.setFont(new java.awt.Font("Microsoft Himalaya", 1, 35)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Check_list de contrôle du dossier transfusionnel ");
        fcontrole.add(jLabel1);
        jLabel1.setBounds(440, 40, 660, 36);

        jLabel78.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel78.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel78.setText("Oui");
        fcontrole.add(jLabel78);
        jLabel78.setBounds(640, 340, 30, 20);

        buttonGroup15.add(veridenoui);
        fcontrole.add(veridenoui);
        veridenoui.setBounds(680, 340, 25, 25);

        jLabel79.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel79.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel79.setText("Non");
        fcontrole.add(jLabel79);
        jLabel79.setBounds(730, 340, 28, 19);

        buttonGroup15.add(veridennon);
        veridennon.setSelected(true);
        fcontrole.add(veridennon);
        veridennon.setBounds(770, 340, 25, 25);

        jTextField1.setEditable(false);
        fcontrole.add(jTextField1);
        jTextField1.setBounds(50, 120, 190, 40);

        jToggleButton1.setLabel("....");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        fcontrole.add(jToggleButton1);
        jToggleButton1.setBounds(240, 120, 40, 40);

        episode.setEditable(false);
        episode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                episodeActionPerformed(evt);
            }
        });
        fcontrole.add(episode);
        episode.setBounds(50, 170, 190, 40);

        jToggleButton2.setText("....");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        fcontrole.add(jToggleButton2);
        jToggleButton2.setBounds(240, 170, 40, 40);

        respost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respostActionPerformed(evt);
            }
        });
        fcontrole.add(respost);
        respost.setBounds(140, 640, 71, 29);

        jMenu1.setText("Identifiant Patient ");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(5, 6, 5, 10));
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu1MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu4.setText("Episode");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu4.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu4.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu4MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu2.setText("Check-list patient");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu2.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu2MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Fiche de contrôle ");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu3.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu3.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu3MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu6.setText("Fiche d'incident");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu6.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu6.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu6MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        jMenu9.setText("Dossier patient");
        jMenu9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu9.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu9.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu9MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu9);

        jMenu5.setText("Quitter");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu5.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu5.setMaximumSize(new java.awt.Dimension(600, 32767));
        jMenu5.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu5MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu8.setText("Utilisateur :");
        jMenu8.setEnabled(false);
        jMenu8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuBar1.add(jMenu8);

        jMenu7.setText("jMenu7");
        jMenu7.setEnabled(false);
        jMenu7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu7.setMargin(new java.awt.Insets(3, 6, 3, 5));
        jMenu7.setMaximumSize(new java.awt.Dimension(500, 32767));
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fcontrole, javax.swing.GroupLayout.PREFERRED_SIZE, 1536, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fcontrole, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void insert(){
           String pres = null;
           String psl=null;
           String nfs=null;
           String gs=null;
           String pheno=null;
           String condtran=null;
           String bondon=null;
           String coniden=null;
           String conform=null;
           String groupepsl=gpsl.getText();
           String datever=null;
           Date date=date1.getDate();
           SimpleDateFormat f =new SimpleDateFormat("dd/MM/yyyy");
           String date2=f.format(date);
           String prosang=null;
           String observs=observ.getText();
           String resulcro=null;
           String painfo=null;
           String veriden=null;
           String poulpree=poulpre.getText();
           String tapree=tapre.getText();
           String tpree=tpre.getText();
           String voie=null;
           String ultime=null;
           String resur=null;
           String rase=ras.getText();
           String intoe=into.getText();
           String connfs=null;
           String respo=respost.getText();
           String tra=null;
           String poulposte=poulpost.getText();
           String taposte=tapost.getText();
           String tposte=tpost.getText();
           String conscience=cons.getText();
          
        
          
  if(presoui.isSelected()){
              pres="Oui";}
           else if(presnon.isSelected()){
               pres="Non";
               
           }
  if(psloui.isSelected()){
              psl="Oui";}
           else if(pslnon.isSelected()){
               psl="Non";
               
         
           }
  if(nfsoui.isSelected()){
              nfs="Oui";}
           else if(nfsnon.isSelected()){
               nfs="Non";
               
         
           }
  if(gsoui.isSelected()){
              gs="Oui";}
           else if(gsnon.isSelected()){
               gs="Non";
               
         
           }
   if(phenooui.isSelected()){
              pheno="Oui";}
           else if(phenonon.isSelected()){
               pheno="Non";
               
         
           }
   if(condtranoui.isSelected()){
              condtran="Oui";}
           else if(condtrannon.isSelected()){
               condtran="Non";
               
         
           }
   if(bondonoui.isSelected()){
              bondon="Oui";}
           else if(bondonnon.isSelected()){
               bondon="Non";
               
         
           }
   if(conidenoui.isSelected()){
              coniden="Oui";}
           else if(conidennon.isSelected()){
               coniden="Non";
               
         
           }
   if(conformoui.isSelected()){
              conform="Oui";}
           else if(conformnon.isSelected()){
               conform="Non";
               
         
           }
   if(dateveroui.isSelected()){
              datever="Oui";}
           else if(datevernon.isSelected()){
              datever="Non";
               
         
           }
   if(prosangoui.isSelected()){
              prosang="Oui";}
           else if(prosangnon.isSelected()){
              prosang="Non";
               
         
           }
     if(resulcrooui.isSelected()){
              resulcro="Oui";}
           else if(resulcronon.isSelected()){
              resulcro="Non";
               
         
           }
     if(painfooui.isSelected()){
              painfo="Oui";}
           else if(painfonon.isSelected()){
              painfo="Non";
               
         
           }
     if(voieoui.isSelected()){
              voie="Oui";}
           else if(voienon.isSelected()){
              voie="Non";
               
         
           }
     if(veridenoui.isSelected()){
              veriden="Oui";}
           else if(veridennon.isSelected()){
              veriden="Non";
               
         
           }
     if(uloui.isSelected()){
              ultime="Oui";}
           else if(ulnon.isSelected()){
              ultime="Non";
               
         
           }
     if(resuroui.isSelected()){
              resur="Oui";}
           else if(resurnon.isSelected()){
              resur="Non";
               
         
           }
      if(connfsoui.isSelected()){
              connfs="Oui";}
           else if(connfsnon.isSelected()){
              connfs="Non";
               
         
           }
     
      if(traoui.isSelected()){
              tra="Oui";}
           else if(tranon.isSelected()){
              tra="Non";
               
         
           }
     
      try{
         
          String sql = "INSERT INTO checkp  VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
   
          pst = conn.prepareStatement(sql);
          
          pst.setString(1,pres);
          pst.setString(2,psl);
          pst.setString(3,nfs);
          pst.setString(4,gs);
          pst.setString(5,pheno);
          pst.setString(6,condtran);
          pst.setString(7,bondon);
          pst.setString(8,coniden);
          pst.setString(9,conform );
          pst.setString(10,groupepsl);
          pst.setString(11,datever);
          pst.setString(12,date2 );
          pst.setString(13,prosang);
          pst.setString(14,observs );
          pst.setString(15,resulcro );
          pst.setString(16,painfo);
          pst.setString(17,veriden );
          pst.setString(18,poulpree);
          pst.setString(19,voie );
          pst.setString(20,ultime );
          pst.setString(21,tapree);
          pst.setString(22,tpree);
          pst.setString(23,resur);
          pst.setString(24,rase);
          pst.setString(25,intoe);
          pst.setString(26,connfs);
          pst.setString(27,respo);
          pst.setString(28,tra);
          pst.setString(29,poulposte );
          pst.setString(30,taposte );
          pst.setString(31,tposte);
          pst.setString(32,conscience);
          pst.setString(33,jTextField1.getText());
          pst.setString(34,episode.getText());
         
          pst.execute();
              JOptionPane.showMessageDialog(null,"enregistrement effectué avec succés");
  
       }     
       catch(SQLException e){
               JOptionPane.showMessageDialog(null,e);
                  }}
    
    
    
    public void update(){
           String pres = null;
           String psl=null;
           String nfs=null;
           String gs=null;
           String pheno=null;
           String condtran=null;
           String bondon=null;
           String coniden=null;
           String conform=null;
           String groupepsl=gpsl.getText();
           String datever=null;
           Date date=date1.getDate();
           SimpleDateFormat f =new SimpleDateFormat("dd/MM/yyyy");
           String date2=f.format(date);
           String prosang=null;
           String observs=observ.getText();
           String resulcro=null;
           String painfo=null;
           String veriden=null;
           String poulpree=poulpre.getText();
           String tapree=tapre.getText();
           String tpree=tpre.getText();
           String voie=null;
           String ultime=null;
           String resur=null;
           String rase=ras.getText();
           String intoe=into.getText();
           String connfs=null;
           String respo=respost.getText();
           String tra=null;
           String poulposte=poulpost.getText();
           String taposte=tapost.getText();
           String tposte=tpost.getText();
           String conscience=cons.getText();
          
        
          
  if(presoui.isSelected()){
              pres="Oui";}
           else if(presnon.isSelected()){
               pres="Non";
               
           }
  if(psloui.isSelected()){
              psl="Oui";}
           else if(pslnon.isSelected()){
               psl="Non";
               
         
           }
  if(nfsoui.isSelected()){
              nfs="Oui";}
           else if(nfsnon.isSelected()){
               nfs="Non";
               
         
           }
  if(gsoui.isSelected()){
              gs="Oui";}
           else if(gsnon.isSelected()){
               gs="Non";
               
         
           }
   if(phenooui.isSelected()){
              pheno="Oui";}
           else if(phenonon.isSelected()){
               pheno="Non";
               
         
           }
   if(condtranoui.isSelected()){
              condtran="Oui";}
           else if(condtrannon.isSelected()){
               condtran="Non";
               
         
           }
   if(bondonoui.isSelected()){
              bondon="Oui";}
           else if(bondonnon.isSelected()){
               bondon="Non";
               
         
           }
   if(conidenoui.isSelected()){
              coniden="Oui";}
           else if(conidennon.isSelected()){
               coniden="Non";
               
         
           }
   if(conformoui.isSelected()){
              conform="Oui";}
           else if(conformnon.isSelected()){
               conform="Non";
               
         
           }
   if(dateveroui.isSelected()){
              datever="Oui";}
           else if(datevernon.isSelected()){
              datever="Non";
               
         
           }
   if(prosangoui.isSelected()){
              prosang="Oui";}
           else if(prosangnon.isSelected()){
              prosang="Non";
               
         
           }
     if(resulcrooui.isSelected()){
              resulcro="Oui";}
           else if(resulcronon.isSelected()){
              resulcro="Non";
               
         
           }
     if(painfooui.isSelected()){
              painfo="Oui";}
           else if(painfonon.isSelected()){
              painfo="Non";
               
         
           }
     if(voieoui.isSelected()){
              voie="Oui";}
           else if(voienon.isSelected()){
              voie="Non";
               
         
           }
     if(veridenoui.isSelected()){
              veriden="Oui";}
           else if(veridennon.isSelected()){
              veriden="Non";
               
         
           }
     if(uloui.isSelected()){
              ultime="Oui";}
           else if(ulnon.isSelected()){
              ultime="Non";
               
         
           }
     if(resuroui.isSelected()){
              resur="Oui";}
           else if(resurnon.isSelected()){
              resur="Non";
               
         
           }
      if(connfsoui.isSelected()){
              connfs="Oui";}
           else if(connfsnon.isSelected()){
              connfs="Non";
               
         
           }
     
      if(traoui.isSelected()){
              tra="Oui";}
           else if(tranon.isSelected()){
              tra="Non";
               
         
           }
     
      try{
         
         String sql ="update checkp set prescription=?,psl=?,nfs=?,gs=?,phenotype=?,conditionstransport=?,bondonneur=?,concordanceidentite=?,concordanceformulaire=?,groupepsl=?,dateverifie=?,date=?,produitsanguin=?,observations=?,resultatcross=?,patientinforme=?,verificationidentite=?,poulepre=?,voieveineuse=?,testultime=?,tapre=?,tpre=?,resultatsurveillance=?,ras=?,intolerance=?,controlenfs=?,resultat=?,tracabilite=?,poulspost=?,tapost=?,tpost=?,etatconscience=? where idpatient=? and episode=?";
          
          pst = conn.prepareStatement(sql);
          
          pst.setString(1,pres);
          pst.setString(2,psl);
          pst.setString(3,nfs);
          pst.setString(4,gs);
          pst.setString(5,pheno);
          pst.setString(6,condtran);
          pst.setString(7,bondon);
          pst.setString(8,coniden);
          pst.setString(9,conform );
          pst.setString(10,groupepsl);
          pst.setString(11,datever);
          pst.setString(12,date2 );
          pst.setString(13,prosang);
          pst.setString(14,observs );
          pst.setString(15,resulcro );
          pst.setString(16,painfo);
          pst.setString(17,veriden );
          pst.setString(18,poulpree);
          pst.setString(19,voie );
          pst.setString(20,ultime );
          pst.setString(21,tapree);
          pst.setString(22,tpree);
          pst.setString(23,resur);
          pst.setString(24,rase);
          pst.setString(25,intoe);
          pst.setString(26,connfs);
          pst.setString(27,respo);
          pst.setString(28,tra);
          pst.setString(29,poulposte );
          pst.setString(30,taposte );
          pst.setString(31,tposte);
          pst.setString(32,conscience);
          pst.setString(33,jTextField1.getText());
          pst.setString(34,episode.getText());
          
          pst.execute();
          
          
              JOptionPane.showMessageDialog(null,"enregistrement effectué avec succés");
         
              
            
             
          
       }     
       catch(SQLException e){
               JOptionPane.showMessageDialog(null,e);
                  }}
    
    
    
  
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(jTextField1.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"Matricule patient non rempli !!!");}
       else if(episode.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"episode non rempli !!!");} 
       else if(gpsl.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"Groupe PSL non rempli !!!");}
       else if(date1.getDate()==null){JOptionPane.showMessageDialog(null,"Date non rempli !!!");}
       else if(observ.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"Observations non rempli !!!");}
       else if(poulpre.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"Pouls pré-transfusion non rempli !!!");}
       else if(tapre.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"TA pré-transfusion non rempli !!!");}
       else if(tpre.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"T° pré-transfusion non rempli !!!");}
       else  if(ras.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"RAS non rempli !!!");}
       else if(into.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"Intolérance non rempli !!!");}
       else if(respost.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"Résultat Post-transfusion non rempli !!!");}
       else if(poulpost.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"Pouls Post-transfusion non rempli !!!");}
       else if(tapost.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"TA Post-transfusion non rempli !!!");}
       else if(tpost.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"T° Post-transfusion non rempli !!!");}
       else if(cons.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"Etat de conscience  Post-transfusion non rempli !!!");}
     
       else{
        
        try{
          String sqlsel ="select * from `checkp` where idpatient= ? and episode=?";
          pstsel = conn.prepareStatement(sqlsel);
          pstsel.setString(1,jTextField1.getText());
          pstsel.setString(2,episode.getText());
          rs=pstsel.executeQuery();
         
          if(!rs.next()){insert();}
          else{update();}
          
          
          
          
         }
        catch(SQLException e){
               JOptionPane.showMessageDialog(null,e);
                  }   } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu1MenuSelected
        patient p=new patient(); 
        p.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu1MenuSelected

    private void jMenu2MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu2MenuSelected
        Check2 c=new Check2();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu2MenuSelected

    private void jMenu3MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu3MenuSelected
        controle c=new controle();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu3MenuSelected

    private void jMenu6MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu6MenuSelected
        declaration c=new declaration();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu6MenuSelected

    private void jMenu5MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu5MenuSelected
        Page1 c=new Page1();
        c.setVisible(true);
        this.hide(); 
    }//GEN-LAST:event_jMenu5MenuSelected

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
       checkpage=1;
       DossierPatient.dossierpatientpage=0;
       episodepage.episodepage1=0;
       declaration.declarationpage=0;
        controle.controlepage=0;
       inpatient p =new inpatient();
       p.show();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        checkpage=1;
        DossierPatient.dossierpatientpage=0;
        episodepage.episodepage1=0;
        declaration.declarationpage=0;
        controle.controlepage=0;
        if(! (inpatient.id==null)){
        episode e=new episode();
        e.show();}
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void episodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_episodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_episodeActionPerformed

    private void jMenu4MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu4MenuSelected
        episodepage c=new episodepage();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu4MenuSelected

    private void jMenu9MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu9MenuSelected
        DossierPatient c=new DossierPatient();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu9MenuSelected

    private void respostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respostActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Check2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JCheckBox bondonnon;
    public static javax.swing.JCheckBox bondonoui;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup15;
    private javax.swing.ButtonGroup buttonGroup16;
    private javax.swing.ButtonGroup buttonGroup17;
    private javax.swing.ButtonGroup buttonGroup18;
    private javax.swing.ButtonGroup buttonGroup19;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup20;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    public static javax.swing.JCheckBox condtrannon;
    public static javax.swing.JCheckBox condtranoui;
    public static javax.swing.JCheckBox conformnon;
    public static javax.swing.JCheckBox conformoui;
    public static javax.swing.JCheckBox conidennon;
    public static javax.swing.JCheckBox conidenoui;
    public static javax.swing.JCheckBox connfsnon;
    public static javax.swing.JCheckBox connfsoui;
    public static javax.swing.JTextField cons;
    public static com.toedter.calendar.JDateChooser date1;
    public static javax.swing.JCheckBox datevernon;
    public static javax.swing.JCheckBox dateveroui;
    public static javax.swing.JTextField episode;
    private javax.swing.JPanel fcontrole;
    public static javax.swing.JTextField gpsl;
    public static javax.swing.JCheckBox gsnon;
    public static javax.swing.JCheckBox gsoui;
    public static javax.swing.JTextField into;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    public static javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    public static javax.swing.JCheckBox nfsnon;
    public static javax.swing.JCheckBox nfsoui;
    public static javax.swing.JTextArea observ;
    public static javax.swing.JCheckBox painfonon;
    public static javax.swing.JCheckBox painfooui;
    public static javax.swing.JCheckBox phenonon;
    public static javax.swing.JCheckBox phenooui;
    public static javax.swing.JTextField poulpost;
    public static javax.swing.JTextField poulpre;
    public static javax.swing.JCheckBox presnon;
    public static javax.swing.JCheckBox presoui;
    public static javax.swing.JCheckBox prosangnon;
    public static javax.swing.JCheckBox prosangoui;
    public static javax.swing.JCheckBox pslnon;
    public static javax.swing.JCheckBox psloui;
    public static javax.swing.JTextField ras;
    public static javax.swing.JTextField respost;
    public static javax.swing.JCheckBox resulcronon;
    public static javax.swing.JCheckBox resulcrooui;
    public static javax.swing.JCheckBox resurnon;
    public static javax.swing.JCheckBox resuroui;
    public static javax.swing.JTextField tapost;
    public static javax.swing.JTextField tapre;
    public static javax.swing.JTextField tpost;
    public static javax.swing.JTextField tpre;
    public static javax.swing.JCheckBox tranon;
    public static javax.swing.JCheckBox traoui;
    public static javax.swing.JCheckBox ulnon;
    public static javax.swing.JCheckBox uloui;
    public static javax.swing.JCheckBox veridennon;
    public static javax.swing.JCheckBox veridenoui;
    public static javax.swing.JCheckBox voienon;
    public static javax.swing.JCheckBox voieoui;
    // End of variables declaration//GEN-END:variables
}
