package transfusionsanguine;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class controle extends javax.swing.JFrame {
    
    Connection conn ;
    PreparedStatement pst,pst2,pstsel,pst3 ;
    ResultSet rs,rs3;
    public static int controlepage=0;
    int k;
    public controle() {
        initComponents();
        conn = Transfusion.conn();
        jMenu7.setText(login1.username);
        nomverif2.setText(login1.username);
        
        
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        fcontrole = new javax.swing.JPanel();
        agnon = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        nomverif1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cont = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        fal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        gpe = new javax.swing.JTextField();
        resmal = new javax.swing.JTextField();
        com = new javax.swing.JComboBox<>();
        Antimal = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        res = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        agoui = new javax.swing.JCheckBox();
        datemal = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jTextField2 = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        grouperh = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        nomverif2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        fcontrole.setBackground(new java.awt.Color(204, 228, 232));
        fcontrole.setLayout(null);

        buttonGroup1.add(agnon);
        agnon.setSelected(true);
        agnon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agnonActionPerformed(evt);
            }
        });
        fcontrole.add(agnon);
        agnon.setBounds(200, 300, 23, 25);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Contrôle du groupe du malade");
        fcontrole.add(jLabel11);
        jLabel11.setBounds(60, 360, 221, 19);

        nomverif1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        nomverif1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fcontrole.add(nomverif1);
        nomverif1.setBounds(560, 270, 160, 0);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Résultat");
        fcontrole.add(jLabel14);
        jLabel14.setBounds(520, 360, 79, 19);
        fcontrole.add(cont);
        cont.setBounds(80, 390, 170, 30);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("CONTROLE DES FLACONS TRANSFUSES :");
        fcontrole.add(jLabel15);
        jLabel15.setBounds(40, 450, 364, 20);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("N° Flacon");
        fcontrole.add(jLabel16);
        jLabel16.setBounds(190, 520, 85, 19);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Compatabilité ");
        fcontrole.add(jLabel17);
        jLabel17.setBounds(340, 360, 106, 19);

        jLabel1.setFont(new java.awt.Font("Microsoft Himalaya", 1, 37)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fiche de contrôle transfusionnel");
        fcontrole.add(jLabel1);
        jLabel1.setBounds(420, 30, 580, 38);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Résultat");
        fcontrole.add(jLabel18);
        jLabel18.setBounds(840, 520, 66, 19);

        fal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                falActionPerformed(evt);
            }
        });
        fcontrole.add(fal);
        fal.setBounds(160, 550, 150, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("CONTROLE PRE TRANSFUSIONNEL :");
        fcontrole.add(jLabel3);
        jLabel3.setBounds(30, 170, 335, 20);

        gpe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpeActionPerformed(evt);
            }
        });
        fcontrole.add(gpe);
        gpe.setBounds(370, 550, 150, 30);

        resmal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resmalActionPerformed(evt);
            }
        });
        fcontrole.add(resmal);
        resmal.setBounds(510, 390, 90, 30);

        com.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anti A", "Anti B", "Anti A+B", "Anti D" }));
        fcontrole.add(com);
        com.setBounds(590, 550, 150, 30);

        Antimal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anti A", "Anti B", "Anti A+B", "Anti D" }));
        Antimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AntimalActionPerformed(evt);
            }
        });
        fcontrole.add(Antimal);
        Antimal.setBounds(340, 390, 105, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Groupe Rhésus figurant sur la carte du  malade");
        fcontrole.add(jLabel7);
        jLabel7.setBounds(50, 220, 350, 19);

        res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resActionPerformed(evt);
            }
        });
        fcontrole.add(res);
        res.setBounds(800, 550, 150, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Agglutinines");
        fcontrole.add(jLabel8);
        jLabel8.setBounds(60, 270, 99, 19);

        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        fcontrole.add(jButton1);
        jButton1.setBounds(1220, 600, 140, 59);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Oui ");
        fcontrole.add(jLabel9);
        jLabel9.setBounds(160, 270, 37, 19);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Groupe");
        fcontrole.add(jLabel19);
        jLabel19.setBounds(410, 520, 70, 20);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Non");
        fcontrole.add(jLabel10);
        jLabel10.setBounds(160, 300, 38, 19);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Compatabilité ");
        fcontrole.add(jLabel20);
        jLabel20.setBounds(610, 520, 106, 19);

        buttonGroup1.add(agoui);
        fcontrole.add(agoui);
        agoui.setBounds(200, 270, 23, 25);
        fcontrole.add(datemal);
        datemal.setBounds(920, 390, 125, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°Falcon", "Groupe", "Compatibilité", "Résultat", "Nom du vérificateur"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        fcontrole.add(jScrollPane1);
        jScrollPane1.setBounds(130, 600, 1060, 220);

        jButton2.setText("Enregistrer fiche contrôle  ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        fcontrole.add(jButton2);
        jButton2.setBounds(1250, 840, 260, 60);

        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        fcontrole.add(jButton3);
        jButton3.setBounds(1220, 660, 140, 59);

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        fcontrole.add(jTextField1);
        jTextField1.setBounds(1220, 80, 190, 40);

        jToggleButton1.setLabel("....");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        fcontrole.add(jToggleButton1);
        jToggleButton1.setBounds(1410, 80, 40, 40);

        jTextField2.setEditable(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        fcontrole.add(jTextField2);
        jTextField2.setBounds(1220, 120, 190, 40);

        jToggleButton2.setText("....");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        fcontrole.add(jToggleButton2);
        jToggleButton2.setBounds(1410, 120, 40, 40);

        grouperh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grouperhActionPerformed(evt);
            }
        });
        fcontrole.add(grouperh);
        grouperh.setBounds(390, 220, 80, 29);

        jLabel21.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Date ");
        fcontrole.add(jLabel21);
        jLabel21.setBounds(950, 360, 60, 20);

        jLabel23.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Nom du vérificateur");
        fcontrole.add(jLabel23);
        jLabel23.setBounds(670, 360, 160, 19);

        nomverif2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        nomverif2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomverif2.setText("nom vérificateur");
        fcontrole.add(nomverif2);
        nomverif2.setBounds(690, 400, 120, 19);

        jMenu1.setText("Identifiant Patient ");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(5, 6, 5, 10));
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu1MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu4.setText("Episode");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu4.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu4.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu4MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu2.setText("Check-list patient");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu2.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu2MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Fiche de contrôle ");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu3.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu3.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu3MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu6.setText("Fiche d'incident");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu6.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu6.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu6MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        jMenu9.setText("Dossier patient");
        jMenu9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu9.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu9.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu9MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu9);

        jMenu5.setText("Quitter");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu5.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu5.setMaximumSize(new java.awt.Dimension(600, 32767));
        jMenu5.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu5MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu8.setText("Utilisateur :");
        jMenu8.setEnabled(false);
        jMenu8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuBar1.add(jMenu8);

        jMenu7.setText("jMenu7");
        jMenu7.setEnabled(false);
        jMenu7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu7.setMargin(new java.awt.Insets(3, 6, 3, 5));
        jMenu7.setMaximumSize(new java.awt.Dimension(500, 32767));
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fcontrole, javax.swing.GroupLayout.DEFAULT_SIZE, 1536, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fcontrole, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resActionPerformed

    private void resmalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resmalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resmalActionPerformed

    private void gpeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpeActionPerformed

    private void falActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_falActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_falActionPerformed

    private void agnonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agnonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agnonActionPerformed
    public void insert(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String controlmal=cont.getText();
        String compat=(String) Antimal.getSelectedItem();
        String resulmal=resmal.getText();
        Date date=datemal.getDate();
        SimpleDateFormat f =new SimpleDateFormat("dd/MM/yyyy");
        String date1=f.format(date);
        String agglu=null;
        if(agoui.isSelected()){
              agglu="Oui";}
           else if(agnon.isSelected()){
              agglu="Non";}
        String gperh=grouperh.getText();
        try{
          String sql ="insert into `controlemalade` (Controlegpe,Compatibilitemalade,Resmalade,Date,Agglutinines,idpatient,episode,grouperhesus,Nomverif) values (?,?,?,?,?,?,?,?,?) ";
          pst = conn.prepareStatement(sql);
          pst.setString(1,controlmal);
          pst.setString(2, compat);
          pst.setString(3, resulmal);
          pst.setString(4, date1);
          pst.setString(5, agglu);
          pst.setString(6, jTextField1.getText());
          pst.setString(7, jTextField2.getText());
          pst.setString(8, gperh);
          pst.setString(9, nomverif2.getText());
          
          pst.execute();
         
          
              JOptionPane.showMessageDialog(null,"enregistrement effectué avec succés");
      
       }     
       catch(SQLException e){
               JOptionPane.showMessageDialog(null,e);
                  }
        try {
       String sql2 = "insert into `controle2` (NFlacon, Groupe, Compatible, Resultat,nomverif,idpatient,episode) values(?,?,?, ?, ?, ?,?)";
       pst2 = conn.prepareStatement(sql2);

        for (int i = 0; i < model.getRowCount(); i++) {
        pst2.setString(1, model.getValueAt(i, 0).toString());
        pst2.setString(2, model.getValueAt(i, 1).toString());
        pst2.setString(3, model.getValueAt(i, 2).toString());
        pst2.setString(4, model.getValueAt(i, 3).toString());
        pst2.setString(5, model.getValueAt(i, 4).toString());
        pst2.setString(6, jTextField1.getText());
        pst2.setString(7, jTextField2.getText());
        pst2.addBatch(); 
       }

        pst2.executeBatch();
      JOptionPane.showMessageDialog(null, "Enregistrement effectué avec succès");}
      catch (SQLException ex) {
      Logger.getLogger(controle.class.getName()).log(Level.SEVERE, null, ex);}
        
    }
    
    
    
    public void update(){
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String controlmal=cont.getText();
        String compat=(String) Antimal.getSelectedItem();
        String resulmal=resmal.getText();
        Date date=datemal.getDate();
        SimpleDateFormat f =new SimpleDateFormat("dd/MM/yyyy");
        String date1=f.format(date);
        String agglu=null;
        if(agoui.isSelected()){
              agglu="Oui";}
           else if(agnon.isSelected()){
              agglu="Non";}
        String gperh=grouperh.getText();
        try{
          String sql ="update `controlemalade` set Controlegpe=?,Compatibilitemalade=?,Resmalade=?,Date=?,Agglutinines=?,grouperhesus=?,Nomverif=? ";
          pst = conn.prepareStatement(sql);
          pst.setString(1,controlmal);
          pst.setString(2, compat);
          pst.setString(3, resulmal);
          pst.setString(4, date1);
          pst.setString(5, agglu);
          pst.setString(6,gperh);
          pst.setString(7, nomverif2.getText());
          pst.execute();
         
          
              JOptionPane.showMessageDialog(null,"enregistrement effectué avec succés");
      
       }     
       catch(SQLException e){
               JOptionPane.showMessageDialog(null,e);
                  }
        int c =jTable1.getModel().getRowCount();
        
        try {
       String sql3 = "DELETE FROM `controle2` WHERE idpatient=? and episode=?";  
       pst3 = conn.prepareStatement(sql3);
       pst3.setString(1, jTextField1.getText());
       pst3.setString(2, controle.jTextField2.getText());
       int rowsAffected = pst3.executeUpdate();  // Use executeUpdate for DELETE
       if (rowsAffected > 0) {
        System.out.println("Deletion successful");
       } else {
        System.out.println("No rows deleted");
       }
      } catch (SQLException ex) {
      Logger.getLogger(controle.class.getName()).log(Level.SEVERE, null, ex);
            } 

    
       try {
       String sql2 = "insert into `controle2` (NFlacon, Groupe, Compatible, Resultat,nomverif,idpatient,episode) values(?,?,?, ?, ?,?, ?)";
       pst2 = conn.prepareStatement(sql2);

        for (int i = 0; i < model.getRowCount(); i++) {
        pst2.setString(1, model.getValueAt(i, 0).toString());
        pst2.setString(2, model.getValueAt(i, 1).toString());
        pst2.setString(3, model.getValueAt(i, 2).toString());
        pst2.setString(4, model.getValueAt(i, 3).toString());
        pst2.setString(4, model.getValueAt(i, 3).toString());
        pst2.setString(5, model.getValueAt(i, 4).toString());
        pst2.setString(6, jTextField1.getText());
        pst2.setString(7, jTextField2.getText());
        pst2.addBatch(); 
       }

        pst2.executeBatch();
      JOptionPane.showMessageDialog(null, "Enregistrement effectué avec succès");}
       
      catch (SQLException ex) {
      Logger.getLogger(controle.class.getName()).log(Level.SEVERE, null, ex);}
    }
    

    
        
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(jTextField1.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"Matricule patient non rempli !!!");}
        else if(jTextField2.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"episode non rempli !!!");} 
        else if(grouperh.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"Groupe Rhésus figurant sur la carte du  malade non rempli !!!");} 
        else if(cont.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"Contrôle du groupe du malade non rempli !!!");}
        else if(Antimal.getSelectedItem()==null){JOptionPane.showMessageDialog(null,"Compatabilité non rempli !!!");}
        else if(resmal.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"Résultat non rempli !!!");}
        else if (datemal.getDate()==null){JOptionPane.showMessageDialog(null,"date non remplie!!!");}
        else  if (jTable1.getModel().getRowCount()==0){JOptionPane.showMessageDialog(null,"Table non remplie!!!");}
         else{ 
        
           
          
         
        try{
          String sqlsel ="select * from `controlemalade` where idpatient= ? and episode=?";
          pstsel = conn.prepareStatement(sqlsel);
          pstsel.setString(1,jTextField1.getText());
          pstsel.setString(2,jTextField2.getText());
          rs=pstsel.executeQuery();
         
          if(!rs.next()){insert();}
          else{
                update();
      
          }
        
          
           }
          
        
        catch(SQLException e){
               JOptionPane.showMessageDialog(null,e);
                  }  
         }
        
    }//GEN-LAST:event_jButton2ActionPerformed
     private void updatetable(){
         
      int i=jTable1.getSelectedRow();
      DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
      if(i>=0){
        model.setValueAt(fal.getText(), i, 0);
        model.setValueAt(gpe.getText(),i,1);
        model.setValueAt(com.getSelectedItem(),i,2);
        model.setValueAt(res.getText(),i,3);
       
      }else{ JOptionPane.showMessageDialog(null,"Error");
     }
     
     }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
       if(k==1){
        updatetable();
        k=0;
       }
       else{ 
        model.addRow(new Object[]{fal.getText(),gpe.getText(),com.getSelectedItem(),res.getText(),nomverif2.getText()});
        fal.setText("");
        gpe.setText("");
        res.setText("");
       }
        
 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
       int r=jTable1.getSelectedRow();
       model.removeRow(r);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu1MenuSelected
        patient p=new patient();
        p.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu1MenuSelected

    private void jMenu2MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu2MenuSelected
        Check2 c=new Check2();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu2MenuSelected

    private void jMenu3MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu3MenuSelected
        controle c=new controle();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu3MenuSelected

    private void jMenu6MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu6MenuSelected
        declaration c=new declaration();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu6MenuSelected

    private void jMenu5MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu5MenuSelected
        Page1 c=new Page1();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu5MenuSelected

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        controlepage=1;
        DossierPatient.dossierpatientpage=0;
        episodepage.episodepage1=0;
        Check2.checkpage=0;
        declaration.declarationpage=0;
        inpatient p =new inpatient();
        p.show();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        controlepage=1;
        DossierPatient.dossierpatientpage=0;
        episodepage.episodepage1=0;
        Check2.checkpage=0;
        declaration.declarationpage=0;
        if(! (inpatient.id==null)){
            episode e=new episode();
            e.show();}
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

   
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int selectedrow=jTable1.getSelectedRow();
       DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
       fal.setText(model.getValueAt(selectedrow,0).toString());
       gpe.setText(model.getValueAt(selectedrow,1).toString());
       com.setSelectedItem(model.getValueAt(selectedrow,2).toString());
       res.setText(model.getValueAt(selectedrow,3).toString());
       k=1;
    }//GEN-LAST:event_jTable1MouseClicked

    private void jMenu4MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu4MenuSelected
        episodepage c=new episodepage();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu4MenuSelected

    private void AntimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AntimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AntimalActionPerformed

    private void jMenu9MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu9MenuSelected
        DossierPatient c=new DossierPatient();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu9MenuSelected

    private void grouperhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grouperhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grouperhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new controle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> Antimal;
    public static javax.swing.JCheckBox agnon;
    public static javax.swing.JCheckBox agoui;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> com;
    public static javax.swing.JTextField cont;
    public static com.toedter.calendar.JDateChooser datemal;
    private javax.swing.JTextField fal;
    private javax.swing.JPanel fcontrole;
    private javax.swing.JTextField gpe;
    public static javax.swing.JTextField grouperh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    public static javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    public static javax.swing.JTextField jTextField1;
    public static javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    public static javax.swing.JLabel nomverif1;
    private javax.swing.JLabel nomverif2;
    private javax.swing.JTextField res;
    public static javax.swing.JTextField resmal;
    // End of variables declaration//GEN-END:variables
}
