package transfusionsanguine;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class declaration extends javax.swing.JFrame {

    Connection conn ;
    PreparedStatement pst,pst2,pstsel,pstsel1;
    ResultSet rs,rssel,rssel1;
    public static int declarationpage=0;
  
    public declaration() {
        initComponents();
        conn = Transfusion.conn();
        jMenu7.setText(login1.username);
        
        
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        fcontrole = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        idpatient = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        episode = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        fcontrole.setBackground(new java.awt.Color(204, 228, 232));
        fcontrole.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Microsoft Himalaya", 1, 37)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fiche de déclaration d'incident transfusionnel");
        fcontrole.add(jLabel1);
        jLabel1.setBounds(200, 50, 1080, 38);

        jButton4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton4.setText("Incident transfusionnel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        fcontrole.add(jButton4);
        jButton4.setBounds(610, 540, 280, 120);

        jButton5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton5.setText("Contrôle pré transfusionnels");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        fcontrole.add(jButton5);
        jButton5.setBounds(320, 300, 280, 120);

        jButton6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton6.setText("Transfusion sanguine");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        fcontrole.add(jButton6);
        jButton6.setBounds(900, 300, 280, 120);

        idpatient.setEditable(false);
        fcontrole.add(idpatient);
        idpatient.setBounds(30, 150, 190, 40);

        jToggleButton1.setLabel("....");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        fcontrole.add(jToggleButton1);
        jToggleButton1.setBounds(220, 150, 40, 40);

        episode.setEditable(false);
        episode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                episodeActionPerformed(evt);
            }
        });
        fcontrole.add(episode);
        episode.setBounds(30, 190, 190, 40);

        jToggleButton2.setText("....");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        fcontrole.add(jToggleButton2);
        jToggleButton2.setBounds(220, 190, 40, 40);

        jMenu1.setText("Identifiant Patient ");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(5, 6, 5, 10));
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu1MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu4.setText("Episode");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu4.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu4.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu4MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu2.setText("Check-list patient");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu2.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu2MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Fiche de contrôle ");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu3.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu3.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu3MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu6.setText("Fiche d'incident");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu6.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu6.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu6MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        jMenu9.setText("Dossier patient");
        jMenu9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu9.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu9.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu9MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu9);

        jMenu5.setText("Quitter");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu5.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu5.setMaximumSize(new java.awt.Dimension(600, 32767));
        jMenu5.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu5MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu8.setText("Utilisateur :");
        jMenu8.setEnabled(false);
        jMenu8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuBar1.add(jMenu8);

        jMenu7.setText("jMenu7");
        jMenu7.setEnabled(false);
        jMenu7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu7.setMargin(new java.awt.Insets(3, 6, 3, 5));
        jMenu7.setMaximumSize(new java.awt.Dimension(500, 32767));
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fcontrole, javax.swing.GroupLayout.DEFAULT_SIZE, 1536, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fcontrole, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(idpatient.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"Matricule non remplie !!!");}
        else if(episode.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"Episode non remplie !!!");}
        else{
             incidenttrans  p;
        try {
            p = new incidenttrans();
            p.setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(declaration.class.getName()).log(Level.SEVERE, null, ex);
        }
            
             this.hide();}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(idpatient.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"Matricule non remplie !!!");}
        else if(episode.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"Episode non remplie !!!");}
        else{
        pretransf p=new pretransf();
        p.setVisible(true);
        this.hide();}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(idpatient.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"Matricule non remplie !!!");}
        else if(episode.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"Episode non remplie !!!");}
        else{
    
        transfusang p = new transfusang();
        p.setVisible(true);
        this.hide();}

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu1MenuSelected
        patient p=new patient();
        p.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu1MenuSelected

    private void jMenu2MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu2MenuSelected
        Check2 c=new Check2();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu2MenuSelected

    private void jMenu3MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu3MenuSelected
        controle c=new controle();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu3MenuSelected

    private void jMenu6MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu6MenuSelected
        declaration c=new declaration();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu6MenuSelected

    private void jMenu5MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu5MenuSelected
        Page1 c=new Page1();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu5MenuSelected

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        declarationpage=1;
        DossierPatient.dossierpatientpage=0;
        episodepage.episodepage1=0;
        controle.controlepage=0;
        Check2.checkpage=0;
        inpatient p =new inpatient();
        p.show();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void episodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_episodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_episodeActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        declarationpage=1;
        DossierPatient.dossierpatientpage=0;
        controle.controlepage=0;
        episodepage.episodepage1=0;
        Check2.checkpage=0;
        if(! (inpatient.id==null)){
            episode e=new episode();
            e.show();}
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jMenu4MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu4MenuSelected
        episodepage c=new episodepage();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu4MenuSelected

    private void jMenu9MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu9MenuSelected
        DossierPatient c=new DossierPatient();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu9MenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new declaration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JTextField episode;
    private javax.swing.JPanel fcontrole;
    public static javax.swing.JTextField idpatient;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    public static javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
