package transfusionsanguine;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;

import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class DossierPatient extends javax.swing.JFrame {

    Connection conn ;
    PreparedStatement pst,pst2;
    ResultSet rs;
    public static int dossierpatientpage=0;
    
    
  
    public DossierPatient() {
        initComponents();
        conn = Transfusion.conn();
        jMenu7.setText(login1.username);
        

            
    
    
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        fcontrole = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usename = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        episode = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        nom = new javax.swing.JLabel();
        prenom = new javax.swing.JLabel();
        datenes = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        nom1 = new javax.swing.JLabel();
        nom2 = new javax.swing.JLabel();
        nom3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        fcontrole.setBackground(new java.awt.Color(204, 228, 232));
        fcontrole.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fcontrole.add(jLabel11);
        jLabel11.setBounds(15, 241, 221, 0);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fcontrole.add(jLabel15);
        jLabel15.setBounds(6, 364, 364, 0);

        jLabel3.setFont(new java.awt.Font("Microsoft Himalaya", 1, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Dossier Patient");
        fcontrole.add(jLabel3);
        jLabel3.setBounds(530, 40, 420, 40);
        fcontrole.add(usename);
        usename.setBounds(837, 10, 140, 30);

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        fcontrole.add(jTextField1);
        jTextField1.setBounds(110, 120, 190, 40);

        jToggleButton1.setLabel("....");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        fcontrole.add(jToggleButton1);
        jToggleButton1.setBounds(300, 120, 40, 40);

        episode.setEditable(false);
        episode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                episodeActionPerformed(evt);
            }
        });
        fcontrole.add(episode);
        episode.setBounds(110, 160, 190, 40);

        jToggleButton2.setText("....");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        fcontrole.add(jToggleButton2);
        jToggleButton2.setBounds(300, 160, 40, 40);

        nom.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        nom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nom.setText("Nom");
        fcontrole.add(nom);
        nom.setBounds(200, 270, 70, 30);

        prenom.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        prenom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        prenom.setText("Prénom");
        fcontrole.add(prenom);
        prenom.setBounds(440, 269, 170, 30);

        datenes.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        datenes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        datenes.setText("Date de naissance");
        fcontrole.add(datenes);
        datenes.setBounds(770, 270, 131, 30);

        jButton1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButton1.setText("Imprimer Check-list patient");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        fcontrole.add(jButton1);
        jButton1.setBounds(330, 460, 300, 80);

        jButton2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButton2.setText("Imprimer accord");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        fcontrole.add(jButton2);
        jButton2.setBounds(850, 600, 300, 80);

        jButton3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButton3.setText("Imprimer fiche d'incident");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        fcontrole.add(jButton3);
        jButton3.setBounds(330, 600, 300, 80);

        jButton4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButton4.setText("Imprimer fiche de contrôle");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        fcontrole.add(jButton4);
        jButton4.setBounds(850, 460, 300, 80);

        nom1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nom1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nom1.setText("Date de naissance :");
        fcontrole.add(nom1);
        nom1.setBounds(600, 270, 170, 30);

        nom2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nom2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nom2.setText("Nom:");
        fcontrole.add(nom2);
        nom2.setBounds(150, 270, 70, 30);

        nom3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nom3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nom3.setText("Prénom :");
        fcontrole.add(nom3);
        nom3.setBounds(360, 270, 100, 30);

        jMenu1.setText("Identifiant Patient ");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(5, 6, 5, 10));
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu1MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu4.setText("Episode");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu4.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu4.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu4MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu2.setText("Check-list patient");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu2.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu2MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Fiche de contrôle ");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu3.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu3.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu3MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu6.setText("Fiche d'incident");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu6.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu6.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu6MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        jMenu9.setText("Dossier patient");
        jMenu9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu9.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu9.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu9MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu9);

        jMenu5.setText("Quitter");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu5.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu5.setMaximumSize(new java.awt.Dimension(600, 32767));
        jMenu5.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu5MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu8.setText("Utilisateur :");
        jMenu8.setEnabled(false);
        jMenu8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuBar1.add(jMenu8);

        jMenu7.setText("jMenu7");
        jMenu7.setEnabled(false);
        jMenu7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu7.setMargin(new java.awt.Insets(3, 6, 3, 5));
        jMenu7.setMaximumSize(new java.awt.Dimension(500, 32767));
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fcontrole, javax.swing.GroupLayout.DEFAULT_SIZE, 1536, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fcontrole, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu1MenuSelected
       patient p=new patient();
       p.setVisible(true);
       this.hide();
    }//GEN-LAST:event_jMenu1MenuSelected

    private void jMenu3MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu3MenuSelected
        controle c=new controle();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu3MenuSelected

    private void jMenu2MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu2MenuSelected
       
        Check2 c=new Check2();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu2MenuSelected

    private void jMenu6MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu6MenuSelected
        declaration c=new declaration();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu6MenuSelected

    private void jMenu5MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu5MenuSelected
        Page1 c=new Page1();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu5MenuSelected

    private void jMenu4MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu4MenuSelected
        episodepage c=new episodepage();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu4MenuSelected

    private void jMenu9MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu9MenuSelected
        DossierPatient c=new DossierPatient();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu9MenuSelected

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        dossierpatientpage=1;
        Check2.checkpage=0;
        episodepage.episodepage1=0;
        declaration.declarationpage=0;
        controle.controlepage=0;
        inpatient p =new inpatient();
        p.show();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void episodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_episodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_episodeActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        dossierpatientpage=1;
        Check2.checkpage=0;
        episodepage.episodepage1=0;
        declaration.declarationpage=0;
        controle.controlepage=0;
        if(! (inpatient.id==null)){
            episode e=new episode();
            e.show();}
       
    }//GEN-LAST:event_jToggleButton2ActionPerformed
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(jTextField1.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"Matricule patient non rempli !!!");}
        else if(episode.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"episode non rempli !!!");} 
        else{
        String ip1 = jTextField1.getText();
      String ep1 = episode.getText();
      conn = null;

      try {
    // Establish your database connection
         conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/transfusion", "root", "787898");

    // Load the JasperDesign (.jrxml) file
         JasperDesign jDesign = JRXmlLoader.load("C:\\Users\\lenovo\\Documents\\NetBeansProjects\\TransfusionSanguine\\build\\classes\\transfusionsanguine\\DosPatient1.jrxml");

    // Compile the report
        JasperReport jReport = JasperCompileManager.compileReport(jDesign);

    // Create a map for the parameters
        Map<String, Object> parameters = new HashMap<>();
        parameters.put("idp", ip1);
        parameters.put("ep", ep1);

    // Fill the report with the database connection as the data source
        JasperPrint jPrint = JasperFillManager.fillReport(jReport, parameters, conn);

    // View or print the report
        JasperViewer.viewReport(jPrint, false); // false to not close the application after closing the viewer
         JasperPrintManager.printReport(jPrint, true); // For direct printing

}        catch (SQLException e) {
            e.printStackTrace();
}       catch (JRException ex) {
             ex.printStackTrace();
} finally {
    if (conn != null) {
        try {
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}

}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String ip1 = jTextField1.getText();
       conn = null;

      try {
    // Establish your database connection
         conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/transfusion", "root", "787898");

    // Load the JasperDesign (.jrxml) file
         JasperDesign jDesign = JRXmlLoader.load("C:\\Users\\lenovo\\Documents\\NetBeansProjects\\TransfusionSanguine\\build\\classes\\transfusionsanguine\\accord.jrxml");

    // Compile the report
        JasperReport jReport = JasperCompileManager.compileReport(jDesign);

    // Create a map for the parameters
        Map<String, Object> parameters = new HashMap<>();
        parameters.put("idp", ip1);
       
    // Fill the report with the database connection as the data source
        JasperPrint jPrint = JasperFillManager.fillReport(jReport, parameters, conn);

    // View or print the report
        JasperViewer.viewReport(jPrint, false); // false to not close the application after closing the viewer
         JasperPrintManager.printReport(jPrint, true); // For direct printing

}        catch (SQLException e) {
            e.printStackTrace();
}       catch (JRException ex) {
             ex.printStackTrace();
} finally {
    if (conn != null) {
        try {
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      if(jTextField1.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"Matricule patient non rempli !!!");}
        else if(episode.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"episode non rempli !!!");} 
        else{
      String ip1 = jTextField1.getText();
      String ep1 = episode.getText();
      conn = null;

      try {
    // Establish your database connection
         conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/transfusion", "root", "787898");

    // Load the JasperDesign (.jrxml) file
         JasperDesign jDesign = JRXmlLoader.load("C:\\Users\\lenovo\\Documents\\NetBeansProjects\\TransfusionSanguine\\build\\classes\\transfusionsanguine\\DosPatient2.jrxml");

    // Compile the report
        JasperReport jReport = JasperCompileManager.compileReport(jDesign);

    // Create a map for the parameters
        Map<String, Object> parameters = new HashMap<>();
        parameters.put("idp", ip1);
        parameters.put("ep", ep1);

    // Fill the report with the database connection as the data source
        JasperPrint jPrint = JasperFillManager.fillReport(jReport, parameters, conn);

    // View or print the report
        JasperViewer.viewReport(jPrint, false); // false to not close the application after closing the viewer
         JasperPrintManager.printReport(jPrint, true); // For direct printing

}        catch (SQLException e) {
            e.printStackTrace();
}       catch (JRException ex) {
             ex.printStackTrace();
} finally {
    if (conn != null) {
        try {
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      if(jTextField1.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"Matricule patient non rempli !!!");}
        else if(episode.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"episode non rempli !!!");} 
        else{
      String ip1 = jTextField1.getText();
      String ep1 = episode.getText();
      conn = null;

      try {
    // Establish your database connection
         conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/transfusion", "root", "787898");

    // Load the JasperDesign (.jrxml) file
         JasperDesign jDesign = JRXmlLoader.load("C:\\Users\\lenovo\\Documents\\NetBeansProjects\\TransfusionSanguine\\build\\classes\\transfusionsanguine\\DosPatient3.jrxml");

    // Compile the report
        JasperReport jReport = JasperCompileManager.compileReport(jDesign);

    // Create a map for the parameters
        Map<String, Object> parameters = new HashMap<>();
        parameters.put("idp", ip1);
        parameters.put("ep", ep1);
        parameters.put("id", login1.userid);

    // Fill the report with the database connection as the data source
        JasperPrint jPrint = JasperFillManager.fillReport(jReport, parameters, conn);

    // View or print the report
        JasperViewer.viewReport(jPrint, false); // false to not close the application after closing the viewer
         JasperPrintManager.printReport(jPrint, true); // For direct printing

}        catch (SQLException e) {
            e.printStackTrace();
}       catch (JRException ex) {
             ex.printStackTrace();
} finally {
    if (conn != null) {
        try {
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}}
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(controle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DossierPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JLabel datenes;
    public static javax.swing.JTextField episode;
    private javax.swing.JPanel fcontrole;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    public static javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    public static javax.swing.JLabel nom;
    public static javax.swing.JLabel nom1;
    public static javax.swing.JLabel nom2;
    public static javax.swing.JLabel nom3;
    public static javax.swing.JLabel prenom;
    public static javax.swing.JLabel usename;
    // End of variables declaration//GEN-END:variables
}
