package transfusionsanguine;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class patient extends javax.swing.JFrame {
 Connection conn ;
 PreparedStatement pst,pst2,pstsel;
 ResultSet rs,rs2,rssel;
 public static int patientpage=0;
    /**
     * Creates new form acceuil
     */
    public patient() {
        initComponents();
        conn = Transfusion.conn();
        autrep.setVisible(false);
        obp.setVisible(false);
        tranp.setVisible(false);
        chirp.setVisible(false);
        jMenu7.setText(login1.username);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        prenom = new javax.swing.JTextField();
        oboui = new javax.swing.JCheckBox();
        matricule = new javax.swing.JTextField();
        chiroui = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        chirnon = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        obnon = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        trannon = new javax.swing.JCheckBox();
        tranoui = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        no = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tranp = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        chirp = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        autrep = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        obp = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        sexef = new javax.swing.JRadioButton();
        sexem = new javax.swing.JRadioButton();
        datenes = new com.toedter.calendar.JDateChooser();
        y = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 228, 232));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Préciser :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 520, 79, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Oui");
        jLabel19.setName("Oui"); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 36, -1));

        jLabel1.setFont(new java.awt.Font("Microsoft Himalaya", 1, 36)); // NOI18N
        jLabel1.setText("IDENTITEE du PATIENT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 319, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Non");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 32, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Matricule :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 154, -1));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Non");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, 32, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Nom ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 154, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Date de Naissance :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 189, -1));

        jLabel22.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Oui");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 480, 36, -1));

        jLabel23.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Non");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 500, 32, -1));

        jLabel24.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Oui");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 36, -1));

        prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomActionPerformed(evt);
            }
        });
        jPanel1.add(prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 135, -1));

        buttonGroup2.add(oboui);
        oboui.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                obouiItemStateChanged(evt);
            }
        });
        oboui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obouiActionPerformed(evt);
            }
        });
        jPanel1.add(oboui, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, -1, -1));

        matricule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculeActionPerformed(evt);
            }
        });
        jPanel1.add(matricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 135, -1));

        buttonGroup4.add(chiroui);
        chiroui.setName("Oui"); // NOI18N
        chiroui.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chirouiItemStateChanged(evt);
            }
        });
        chiroui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chirouiActionPerformed(evt);
            }
        });
        jPanel1.add(chiroui, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 480, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Sexe :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 69, -1));

        buttonGroup4.add(chirnon);
        chirnon.setSelected(true);
        chirnon.setName("Non"); // NOI18N
        chirnon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chirnonActionPerformed(evt);
            }
        });
        jPanel1.add(chirnon, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 500, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("F");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        buttonGroup2.add(obnon);
        obnon.setSelected(true);
        obnon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obnonActionPerformed(evt);
            }
        });
        jPanel1.add(obnon, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("M");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 30, -1));

        buttonGroup3.add(trannon);
        trannon.setSelected(true);
        trannon.setName("Non"); // NOI18N
        trannon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trannonActionPerformed(evt);
            }
        });
        jPanel1.add(trannon, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, -1, -1));

        buttonGroup3.add(tranoui);
        tranoui.setName("Oui"); // NOI18N
        tranoui.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tranouiItemStateChanged(evt);
            }
        });
        tranoui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tranouiActionPerformed(evt);
            }
        });
        jPanel1.add(tranoui, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText(" Diagnostic médical :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 189, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText(" Antécédents : ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 189, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Obstétricaux :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 110, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Transfusionnels : ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 146, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Chirurgicaux :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 480, 124, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Préciser :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 79, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Autres (préciser) : ");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 480, 140, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Préciser :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, 79, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Prénom ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 180, -1));
        jPanel1.add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 135, -1));

        tranp.setColumns(20);
        tranp.setRows(5);
        jScrollPane1.setViewportView(tranp);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 230, 180));

        chirp.setColumns(20);
        chirp.setRows(5);
        jScrollPane2.setViewportView(chirp);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 560, 230, 180));

        autrep.setColumns(20);
        autrep.setRows(5);
        jScrollPane3.setViewportView(autrep);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 560, 230, 180));

        obp.setColumns(20);
        obp.setRows(5);
        jScrollPane4.setViewportView(obp);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 230, 180));

        jButton1.setActionCommand("Enregistrer");
        jButton1.setLabel("Enregistrer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 790, 220, 60));

        buttonGroup1.add(sexef);
        sexef.setName("F"); // NOI18N
        sexef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexefActionPerformed(evt);
            }
        });
        jPanel1.add(sexef, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        buttonGroup1.add(sexem);
        sexem.setSelected(true);
        sexem.setName("M"); // NOI18N
        jPanel1.add(sexem, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));
        jPanel1.add(datenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 130, -1));

        y.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yItemStateChanged(evt);
            }
        });
        jPanel1.add(y, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 480, -1, -1));

        jButton2.setText(".......");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 40, -1));

        jMenu1.setText("Identifiant Patient ");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(5, 6, 5, 10));
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu1MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu4.setText("Episode");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu4.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu4.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu4MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu2.setText("Check-list patient");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu2.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu2MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Fiche de contrôle ");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu3.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu3.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu3MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu6.setText("Fiche d'incident");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu6.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu6.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu6MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        jMenu9.setText("Dossier patient");
        jMenu9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu9.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu9.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu9MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu9);

        jMenu5.setText("Quitter");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu5.setMargin(new java.awt.Insets(5, 10, 5, 10));
        jMenu5.setMaximumSize(new java.awt.Dimension(600, 32767));
        jMenu5.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu5MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu8.setText("Utilisateur :");
        jMenu8.setEnabled(false);
        jMenu8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuBar1.add(jMenu8);

        jMenu7.setText("jMenu7");
        jMenu7.setEnabled(false);
        jMenu7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu7.setMargin(new java.awt.Insets(3, 6, 3, 5));
        jMenu7.setMaximumSize(new java.awt.Dimension(500, 32767));
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomActionPerformed

    private void obouiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obouiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obouiActionPerformed

    private void matriculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculeActionPerformed

    private void chirouiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chirouiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chirouiActionPerformed

    private void chirnonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chirnonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chirnonActionPerformed

    private void obnonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obnonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obnonActionPerformed

    private void trannonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trannonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trannonActionPerformed

    private void tranouiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tranouiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tranouiActionPerformed
    public void insert(){
    
    
     String id=matricule.getText();
           String nom=no.getText();
           String pre=prenom.getText();
           Date date=datenes.getDate();
           SimpleDateFormat f =new SimpleDateFormat("dd/MM/yyyy");
           String date2=f.format(date);
           String sexe = null;
           String ob=null;
           String tran=null;
           String chir=null;
          
  if(sexem.isSelected()){
              sexe="M";}
           else if(sexef.isSelected()){
               sexe="F";
               
         
           }
           
  if(oboui.isSelected()){
               ob="Oui";}
           else if(obnon.isSelected()){
                ob="Non";
               
           }
  
   if(tranoui.isSelected()){
              tran="Oui";}
           else if(trannon.isSelected()){
                tran="Non";
               
           }
   if(chiroui.isSelected()){
               chir="Oui";}
           else if(chirnon.isSelected()){
               chir="Non";
               
           }
   
    String obpre=obp.getText();
    String tranpre=tranp.getText();
    String chirpre=chirp.getText();
    String autrepre=autrep.getText();
    
    System.out.print(sexe);
    System.out.print(tran);
      try{
          String sql ="insert into patient (id,nom,prenom,datenes,sexe) values (?,?,?,?,?) ";
          pst = conn.prepareStatement(sql);
          pst.setString(1,id);
          pst.setString(2, nom);
          pst.setString(3, pre);
          pst.setString(4, date2);
          pst.setString(5, sexe);
          pst.execute();
          String sql2 ="insert into antecedents(idpatient,obstetricaux,p_obstetricaux,transfusionnels,p_transfusionnels,chirurgicaux,p_chirurgicaux,autresp) values (?,?,?,?,?,?,?,?) ";
          pst2 = conn.prepareStatement(sql2);
          pst2.setString(1,id);
          pst2.setString(2, ob);
          pst2.setString(3, obpre);
          pst2.setString(4, tran);
          pst2.setString(5, tranpre);
          pst2.setString(6,chir);
          pst2.setString(7, chirpre);
          pst2.setString(8,autrepre);
          pst2.execute();
          
              JOptionPane.showMessageDialog(null,"enregistrement effectué avec succés");
         
              
            
             
          
       }     
       catch(SQLException e){
               JOptionPane.showMessageDialog(null,e);
                  }
        
    
    
    
    
    
    
    
    
    
    }
    public void update(){
    
     String id=matricule.getText();
           String nom=no.getText();
           String pre=prenom.getText();
           Date date=datenes.getDate();
           SimpleDateFormat f =new SimpleDateFormat("dd/MM/yyyy");
           String date2=f.format(date);
           String sexe = null;
           String ob=null;
           String tran=null;
           String chir=null;
          
  if(sexem.isSelected()){
              sexe="M";}
           else if(sexef.isSelected()){
               sexe="F";
               
         
           }
           
  if(oboui.isSelected()){
               ob="Oui";}
           else if(obnon.isSelected()){
                ob="Non";
               
           }
  
   if(tranoui.isSelected()){
              tran="Oui";}
           else if(trannon.isSelected()){
                tran="Non";
               
           }
   if(chiroui.isSelected()){
               chir="Oui";}
           else if(chirnon.isSelected()){
               chir="Non";
               
           }
   
    String obpre=obp.getText();
    String tranpre=tranp.getText();
    String chirpre=chirp.getText();
    String autrepre=autrep.getText();
    
    System.out.print(sexe);
    System.out.print(tran);
      try{
          String sql ="update patient set nom=?, prenom=? , datenes=?, sexe=? where id =? ";
          pst = conn.prepareStatement(sql);
          pst.setString(1, nom);
          pst.setString(2, pre);
          pst.setString(3, date2);
          pst.setString(4, sexe);
          pst.setString(5,id);
          pst.execute();
          String sql2 ="update antecedents set obstetricaux=? , p_obstetricaux=? ,transfusionnels=? , p_transfusionnels=? , chirurgicaux=? , p_chirurgicaux=? , autresp=? where idpatient=? ";
          pst2 = conn.prepareStatement(sql2);
         
          pst2.setString(1, ob);
          pst2.setString(2, obpre);
          pst2.setString(3, tran);
          pst2.setString(4, tranpre);
          pst2.setString(5,chir);
          pst2.setString(6, chirpre);
          pst2.setString(7,autrepre);
          pst2.setString(8,id);
          pst2.execute();
          
              JOptionPane.showMessageDialog(null,"enregistrement effectué avec succés");
         
              
            
             
          
       }     
       catch(SQLException e){
               JOptionPane.showMessageDialog(null,e);
                  }
        
    
    
    
    
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(matricule.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"Matricule patient non rempli !!!");}
        else if(no.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"Nom non rempli !!!");} 
        else if(prenom.getText().trim().isEmpty()){JOptionPane.showMessageDialog(null,"Prénom non rempli !!!");}
        else if(datenes.getDate()==null){JOptionPane.showMessageDialog(null,"Date naissance non rempli !!!");}
        
        else{
        
         String mat =matricule.getText();
         try{
          String sqlsel ="select * from patient where id = ? ";
          pstsel = conn.prepareStatement(sqlsel);
          pstsel.setString(1,mat);
          rssel=pstsel.executeQuery();
         
          if(!rssel.next()){insert();}
          else{update();}
          
          
          
          
         }
        catch(SQLException e){
               JOptionPane.showMessageDialog(null,e);
                  }}
        
        
        
        
        
        
        
             
          
      
        
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void yItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yItemStateChanged
         if(y.isSelected()==true){
            autrep.setVisible(true);}
        else{
            autrep.setVisible(false);
        }
         
    }//GEN-LAST:event_yItemStateChanged

    private void obouiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_obouiItemStateChanged
          if(oboui.isSelected()==true){
            obp.setVisible(true);}
        else{
            obp.setVisible(false);
        }
    }//GEN-LAST:event_obouiItemStateChanged

    private void chirouiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chirouiItemStateChanged
      if(chiroui.isSelected()==true){
            chirp.setVisible(true);}
        else{
            chirp.setVisible(false);
        }                                        
        
    }//GEN-LAST:event_chirouiItemStateChanged

    private void tranouiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tranouiItemStateChanged
        if(tranoui.isSelected()==true){
            tranp.setVisible(true);}
        else{
            tranp.setVisible(false);
        }                      
    }//GEN-LAST:event_tranouiItemStateChanged

    private void jMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu1MenuSelected
        patient p=new patient();
        p.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu1MenuSelected

    private void jMenu2MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu2MenuSelected
        Check2 c=new Check2();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu2MenuSelected

    private void jMenu3MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu3MenuSelected
        controle c1=new controle();
        c1.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu3MenuSelected

    private void jMenu6MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu6MenuSelected
        declaration c2=new declaration();
        c2.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu6MenuSelected

    private void jMenu5MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu5MenuSelected
        Page1 c3=new Page1();
        c3.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu5MenuSelected

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        inpatient1 p =new inpatient1();
        p.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void sexefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexefActionPerformed

    private void jMenu4MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu4MenuSelected
        episodepage c=new episodepage();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu4MenuSelected

    private void jMenu9MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu9MenuSelected
        DossierPatient c=new DossierPatient();
        c.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenu9MenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea autrep;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    public static javax.swing.JCheckBox chirnon;
    public static javax.swing.JCheckBox chiroui;
    public static javax.swing.JTextArea chirp;
    public static com.toedter.calendar.JDateChooser datenes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    public static javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTextField matricule;
    public static javax.swing.JTextField no;
    public static javax.swing.JCheckBox obnon;
    public static javax.swing.JCheckBox oboui;
    public static javax.swing.JTextArea obp;
    public static javax.swing.JTextField prenom;
    public static javax.swing.JRadioButton sexef;
    public static javax.swing.JRadioButton sexem;
    public static javax.swing.JCheckBox trannon;
    public static javax.swing.JCheckBox tranoui;
    public static javax.swing.JTextArea tranp;
    public static javax.swing.JCheckBox y;
    // End of variables declaration//GEN-END:variables
}
